apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: ewallet
spec:
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigwcontainer
          image: apigw:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80

