apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-deployment
  namespace: ewallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sagamachine
  template:
    metadata:
      labels:
        app: sagamachine
    spec:
      containers:
        - name: ewalletsaga
          image: ewalletsaga:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
          env:
                - name: ConnectionStrings__DefaultConnection
                  valueFrom:
                    secretKeyRef:
                      name: ewalletdb
                      key: DbConnectionString

                - name: QueueSettings__HostName
                  value: rabbit-release-rabbitmq
                - name: QueueSettings__VirtualHost
                  value: /
                - name: QueueSettings__UserName
                  value: user
                - name: QueueSettings__Password
                  valueFrom:
                    secretKeyRef:
                      name: rabbit-release-rabbitmq
                      key: rabbitmq-password
