apiVersion: v1
kind: Service
metadata:
  name: identityserver-app
  namespace: ewallet
spec:
  selector:
    app: identityserver
  ports:
    - name: http
      protocol: TCP
      port: 2509
      targetPort: 80
  type: LoadBalancer
