kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: externalnidserver-data-claim
  namespace: ewallet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem