apiVersion: v1
kind: Service
metadata:
  name: kycservice
  namespace: ewallet
spec:
  selector:
    app: kycservice
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: kycservice-ex
  namespace: ewallet
spec:
  selector:
    app: kycservice
  ports:
    - port: 8087
      targetPort: 80
  type: LoadBalancer
