apiVersion: apps/v1
kind: Deployment
metadata:
  name: kycservice-deployment
  namespace: ewallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kycservice
  template:
    metadata:
      labels:
        app: kycservice
    spec:
      containers:
        - name: kycservice
          image: kycservice:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
          env:
                - name: ConnectionStrings__DefaultConnection
                  value: Server=ewallet-db,80;Database=KycService;User=sa;Password=Password!2;MultipleActiveResultSets=true;

                - name: QueueSettings__HostName
                  value: rabbit-release-rabbitmq
                - name: QueueSettings__VirtualHost
                  value: /
                - name: QueueSettings__UserName
                  value: user
                - name: QueueSettings__Password
                  valueFrom:
                    secretKeyRef:
                      name: rabbit-release-rabbitmq
                      key: rabbitmq-password
