---
apiVersion: v1
kind: Service
metadata:
  name: nidserver
  namespace: ewallet
spec:
  selector:
    app: nid-server
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nidserver-ex
  namespace: ewallet
spec:
  selector:
    app: nid-server
  ports:
    - port: 3001
      targetPort: 80
  type: LoadBalancer