apiVersion: v1
kind: Service
metadata:
  name: rewardservice
  namespace: ewallet
spec:
  selector:
    app: rewardservice
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: rewardservice-ex
  namespace: ewallet
spec:
  selector:
    app: rewardservice
  ports:
    - port: 8088
      targetPort: 80
  type: LoadBalancer


