// <auto-generated />
using System;
using Kyc.Insfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kyc.API.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200818085948_InitMigrations")]
    partial class InitMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kyc.Domain.AggregateModel.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CountryGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryGuid = new Guid("dab5f416-e25a-43e4-a277-5cfe92b7ae30"),
                            CurrencyCode = "BDT",
                            IsoCode = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 2,
                            CountryGuid = new Guid("0b5e1eaa-bfae-44cb-8eba-752bb95ef359"),
                            CurrencyCode = "INR",
                            IsoCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 3,
                            CountryGuid = new Guid("bd50407e-ec38-4cb0-bf23-f198c7d0097e"),
                            CurrencyCode = "NOK",
                            IsoCode = "NO",
                            Name = "Norway"
                        });
                });

            modelBuilder.Entity("Kyc.Domain.AggregateModel.KycInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("KycStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KycStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Kycs");
                });

            modelBuilder.Entity("Kyc.Domain.AggregateModel.KycStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KycStatuses");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("Kyc.Domain.AggregateModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsKycVerified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kyc.Domain.AggregateModel.KycInformation", b =>
                {
                    b.HasOne("Kyc.Domain.AggregateModel.KycStatus", "KycStatus")
                        .WithMany()
                        .HasForeignKey("KycStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kyc.Domain.AggregateModel.User", "User")
                        .WithMany("KycInformations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kyc.Domain.AggregateModel.User", b =>
                {
                    b.HasOne("Kyc.Domain.AggregateModel.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
