apiVersion: v1
kind: Service
metadata:
  name: ewallet-db-ex
  namespace: ewallet
spec:
  selector:
    app: sqlserverdeployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 1433
  type: LoadBalancer
