apiVersion: v1
kind: Service
metadata:
  name: ewallet-db
  namespace: ewallet
spec:
  selector:
    app: sqlserverdeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1433
  type: ClusterIP
