version: "3.4"

services:
  identityserver:
    image: identityserver:latest
    build:
      context: .
      dockerfile: Services/Identity/IdentityServerAspNetIdentity/Dockerfile
    environment:
      ConnectionStrings:DefaultConnection: "Data Source=wallet-db;database=AuthServer;MultipleActiveResultSets=true;"
    #depends_on:
    #- identity-db
    #- externalnidserver
    ports:
      - 80:80
      - 443:443
  kycservice:
    image: kycservice:latest
    build:
      context: .
      dockerfile: Services/Kyc/Kyc.API/Kyc.API/Dockerfile
    environment:
      ConnectionStrings:DefaultConnection: "Data Source=wallet-db;database=Kyc-db;MultipleActiveResultSets=true;"
    #depends_on:
    #- identity-db
    #- externalnidserver
    ports:
      - 80:80

  transactionservice:
    image: transactionservice:latest
    build:
      context: .
      dockerfile: Services/Transaction/Transaction.API/Dockerfile
    environment:
      ConnectionStrings:DefaultConnection: "Data Source=wallet-db;database=transaction-db;MultipleActiveResultSets=true;"
    ports:
      - 6012:80
  apigw:
    image: apigw:latest
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile
  rewardservice:
    image: rewardservice:latest
    build:
      context: .
      dockerfile: Services/Reward/Reward.API/Dockerfile
    environment:
      ConnectionStrings:DefaultConnection: "Data Source=wallet-db;database=reward-db;MultipleActiveResultSets=true;"
    ports:
      - 6012:80
volumes:
  sqlvolume:
